### ISSUE TITLE
GetValues: Support WaterML 2.0

### ISSUE THREAD

**Issue by jirikadlec2** [jirikadlec2/waterml#3]
In the GetValues function, recognize if the WaterML data is WaterML 2.0 and parse it correctly

**Comment by ldecicco-USGS** [comment]
2.0 is another beast entirely. I started working on it a bit for the `dataRetrieval` package. If you want to have a look at start, it's here:

https://github.com/USGS-R/dataRetrieval/blob/master/R/importWaterML2.r

You'll notice for both WaterML1 and 2 retrievals (getValues vs importWaterML1), we've got a lot of duplicated code. If you ever start getting into timezone issues, metadata on the values (comments/qualifiers/etc), you might consider depending on dataRetrieval (ie. Imports). If there are issues that you think prevent that, but you like the idea, create an Issue on the dataRetrieval page, I bet we could make that happen.

**Comment by jirikadlec2** [comment]
This is a very good suggestion. I like the idea of depending on dataRetrieval and re-using the importWaterML2 / importWaterML1 functions from the dataRetrieval package. I've been trying it out with different WaterML files, but I'm having issues in importWaterML2: https://github.com/USGS-R/dataRetrieval/issues/131
The importWaterML2 almost works, but it fails when my WaterML2 file has 0 gml:identifier or more than 1 gml:identifier.

**Comment by jirikadlec2** [comment]
Basic support for WaterML 2.0 has been added in 1.4 
I couldn't reuse USGS-R/dataRetrieval at this moment, because it depends on plyr and many users had trouble with plyr installation when installing the WaterML R package. More testing of different varieties of WaterML 2.0 is needed in future version.

**Comment by ldecicco-USGS** [comment]
Sounds good. I have been looking into removing that plyr dependency. I may bump that up in priority. Thanks!
